dist: trusty
sudo: required
addons:
  chrome: stable
  firefox: latest
language: node_js
node_js:
- stable
branches:
  only:
  - develop
before_script:
- npm install -g @angular/cli
- npm install
script:
- ng test --watch=false
- mocha --recursive src/app/tests
deploy:
  provider: heroku
  api_key:
    secure: cVn+8wKn8WGfYYdjBIhWuw0m0Bx5zBZ9FecxN57IXYdGEYtF7o2+5lwxf3POcB7oLAqs/0Y/kbkxKjjQDSe2fLe/fwZBfcuLhO0WC+ZFsyLyUHPDGqNZk5aceYN8zibZB9pa+awi1kqQu81xeMmmi+Rodf1JKjbRls7bAbUvon9nsc6FbnHS5xbLqJHXIhs5UlLxqKzYUyoa72GhoGdSHC7eZjr3Ybf8yOssv3dwukTNlSOcHz6qUwoxwBrbetUpKn8KwdGcvEPYlvtks6N0jRtcLPcgsqnn3W7uOh8dbrqdSzLI7Xshe2C5KUJ3NJRICg4G+P821F9wPTUSNp0M6H6fMM5+qadEHPgz2BbeE7PwKvy2dA2Veg1ZSYTxGjoQIBOM7X7I1ooloRbSgHqC+6VWqnriEpxVNdMdN+S+KKyMkso1D+tJRq63T4ytT554jYhHKuEyrklfBhdUajDjFX5gsNP3gR4JrhDMxptqEzhy85UgKNFiQghV+sed2RVkPehzw06cV6C8cbIdf2PEN9kbwmoixEDAKRsGliBPshvuVzKeqvUhZ6VNHKPRjAJasXLQKoQHYasuac02pxJ6L0TbabrBOxKRCA3mnzoVxbLjDHWuKxdw7bpW01rV+ACBwXZxCSW/18Yq9FlQ7Pkw7XVlCE4WQcDsHhGMxHk/cq4=
  app: isa-tfg
  on:
    repo: estagumor/TFG-18-19
cache:
  directories:
  - "./node_modules"
install:
- npm install
