dist: trusty
sudo: required
addons:
  chrome: stable
language: node_js
node_js:
- stable
branches:
  only:
  - develop
before_script:
- npm install -g @angular/cli
script:
- ng test --watch=false
deploy:
  provider: heroku
  api_key:
    secure: dBce/KNt+LHmHBufiIjzvUx5JBvJgeh4ttsn8EnOhFKiCa9pKKwjxs1PiV4a1VXM4b1wTBoQMNag6MSExkPYcu6x33xmt1lj21Kmlpe91Qcc3LF+G6hS4zJBKTECeDLvxXkPfaH9aOu5U3QhJdw8eTt5KV7RT6mQOwmuTq3qrNpqUjqx25eIWSPjzcVzyXse3s50UrdSmqtuoOI0oYAtLDRadKknHKp7gXIibTxtPQ9qjFN8+H4jQyS+qrbu3E8Ho5Efu4CNCHEXh6XniTF3WKb1z6L3v+lK8TBJD7T5PbaZ0pwXPuRNbxpGHk3y+WjE9b/AnMf4c6H0Y45IVvKd6woPfOshNsxRDDkzNPfJPqA0JGKHuvQMnNnq1eLGeNMCxzikyiHZGYgfVcBk0sbL8J+r6bgln8OvCABYhHsPSJA6DKO7lgD+ajVx7o4JOezmItGf7brtYX1lcd67yywaph933aB3A0q4jfBeCyc9F/yFVWEL07gLeNd/y5cIZeyGigmfxxjibua2kGqcbSdnwLPelT+QubJKNIlazyXKg8F2pr1lvGqCi8RPvBywKDvwVinoGBqJcLww78tyi15OKw9ln6fucKzVKwNpFpSMn5StZylw+7g8S2WmhEXHEAsOdwgSXqV4Hh7U/+de0sVwVdbKYCeHZXCAKfCgLva8Y5k=
  app: isa-tfg
  on:
    repo: Wordsan/TFG-18-19
    branch: develop
cache:
  directories:
  - "./node_modules"
install:
- npm install
