dist: trusty
sudo: required
addons:
  chrome: stable
language: node_js
node_js:
- stable
branches:
  only:
  - develop
before_script:
- npm install -g @angular/cli
- npm install
script:
- ng test --watch=false
- mocha --recursive src/app/tests
deploy:
  provider: heroku
  api_key:
    secure: jmljU/gdR7Ad24lFiFvB3QRVJQeld8aZgFV8B34GV6azfOs6+EfmGk3mSQYKKFAEtRZZGhFHP2MyyKMs2Tuq7qvStniQeVTq5Qv8KOOP/YsxfxPfjWuwltHNc99aH9mbBq5pzguyLqAPk/mT6o3mpjMFsuQMze3x8JI3wEMozuCUhiUSwarXqb2IvZzEGsEWIpkXbR6ye9SSst8YABcmXkufJArfv46gJ6lO5m0U45GsIPbuxkDieWmhAJYlWuPggSI+G8TYE6BRkTXOA9mamowJRxRRCkq55Bb3YBp9xSfbyjqb4ZRQN38JUcBhN3bsCqNuD+P2najfDu5o/GBHTuR07SWtFrxlxBrsdk7k2chOrx9nMgUpif7kqa8aR3gZJPIZVkTbCPahRwuPcJVAE3HLa9LhpJJawbZS+WahKzKtISeo9fU2MSlXEsJSQl4cKTvMvif/o5SfcQTuH7ooiuJVKs8UX3j2zkspcfgeTD6NnylvT6ZKvQS1EFmfeYr9eqmXBoLDnYMqO+sIfMBYne/IWYtD0sw0qYk79S39Bz/AfpxLafJBfMuw/8WzX62S9hmcypqDd/217t8v1U4YahI+uW4pTDSv625Yb//sDYpI/kpmKHj0UplWhTPm9NG/g5G4b1CpDrql8uAvSF3XFxoD19kpB19Oc2Ri67KgWHQ=
  app: isa-tfg
  on:
    repo: estagumor/TFG-18-19
    branch: develop
cache:
  directories:
  - "./node_modules"
install:
- npm install
