dist: trusty
sudo: required
addons:
  chrome: stable

language: node_js
node_js:
  - stable

branches:
  only:
  - develop

before_script:
  - npm install -g @angular/cli

script: 
  - ng test --watch=false
  #- npm run e2e

deploy:
  provider: heroku
  api_key:
    secure: 90414A18B0B3B696E96323EA8DB68307493AA47B4C146A188D37B5C72795D56A,9BBE8016F668625E8840D4002C6490A353E3E19BF8E4E5126F4F096114B44B4E
  on: develop
 
cache:
  directories:
     - ./node_modules
 
install:
  - npm install